#!/bin/bash

set -e

if ! which uv > /dev/null; then
    echo "uv is not installed"
    exit 1
fi

ROOT=$(git rev-parse --show-toplevel)

uv run cpplint --quiet --recursive "${ROOT}"
uv run ruff check "$ROOT"
