/*
    *   Copyright 2025 Team Arboris
    *   Licensed under the Apache License, Version 2.0
    *   http://www.apache.org/licenses/LICENSE-2.0
    */

#include <unordered_map>

#include "utils/tag.h"

namespace arboris {

Tags from_string(std::string_view tag_name) {
  static const std::unordered_map<std::string_view, Tags> tag_map = {
      {"a", Tags::kA},
      {"abbr", Tags::kAbbr},
      {"address", Tags::kAddress},
      {"area", Tags::kArea},
      {"article", Tags::kArticle},
      {"aside", Tags::kAside},
      {"audio", Tags::kAudio},
      {"b", Tags::kB},
      {"base", Tags::kBase},
      {"bdi", Tags::kBdi},
      {"bdo", Tags::kBdo},
      {"blockquote", Tags::kBlockquote},
      {"body", Tags::kBody},
      {"br", Tags::kBr},
      {"button", Tags::kButton},
      {"canvas", Tags::kCanvas},
      {"caption", Tags::kCaption},
      {"cite", Tags::kCite},
      {"code", Tags::kCode},
      {"col", Tags::kCol},
      {"colgroup", Tags::kColgroup},
      {"data", Tags::kData},
      {"datalist", Tags::kDatalist},
      {"dd", Tags::kDd},
      {"del", Tags::kDel},
      {"details", Tags::kDetails},
      {"dfn", Tags::kDfn},
      {"dialog", Tags::kDialog},
      {"div", Tags::kDiv},
      {"dl", Tags::kDl},
      {"dt", Tags::kDt},
      {"em", Tags::kEm},
      {"embed", Tags::kEmbed},
      {"fieldset", Tags::kFieldset},
      {"figcaption", Tags::kFigcaption},
      {"figure", Tags::kFigure},
      {"footer", Tags::kFooter},
      {"form", Tags::kForm},
      {"h1", Tags::kH1},
      {"h2", Tags::kH2},
      {"h3", Tags::kH3},
      {"h4", Tags::kH4},
      {"h5", Tags::kH5},
      {"h6", Tags::kH6},
      {"head", Tags::kHead},
      {"header", Tags::kHeader},
      {"hgroup", Tags::kHgroup},
      {"hr", Tags::kHr},
      {"html", Tags::kHtml},
      {"i", Tags::kI},
      {"iframe", Tags::kIframe},
      {"img", Tags::kImg},
      {"input", Tags::kInput},
      {"ins", Tags::kIns},
      {"kbd", Tags::kKbd},
      {"label", Tags::kLabel},
      {"legend", Tags::kLegend},
      {"li", Tags::kLi},
      {"link", Tags::kLink},
      {"main", Tags::kMain},
      {"map", Tags::kMap},
      {"mark", Tags::kMark},
      {"menu", Tags::kMenu},
      {"meta", Tags::kMeta},
      {"meter", Tags::kMeter},
      {"nav", Tags::kNav},
      {"noscript", Tags::kNoscript},
      {"object", Tags::kObject},
      {"ol", Tags::kOl},
      {"optgroup", Tags::kOptgroup},
      {"option", Tags::kOption},
      {"output", Tags::kOutput},
      {"p", Tags::kP},
      {"picture", Tags::kPicture},
      {"pre", Tags::kPre},
      {"progress", Tags::kProgress},
      {"q", Tags::kQ},
      {"rp", Tags::kRp},
      {"rt", Tags::kRt},
      {"ruby", Tags::kRuby},
      {"s", Tags::kS},
      {"samp", Tags::kSamp},
      {"script", Tags::kScript},
      {"search", Tags::kSearch},
      {"section", Tags::kSection},
      {"select", Tags::kSelect},
      {"small", Tags::kSmall},
      {"source", Tags::kSource},
      {"span", Tags::kSpan},
      {"strong", Tags::kStrong},
      {"style", Tags::kStyle},
      {"sub", Tags::kSub},
      {"summary", Tags::kSummary},
      {"sup", Tags::kSup},
      {"table", Tags::kTable},
      {"tbody", Tags::kTbody},
      {"td", Tags::kTd},
      {"template", Tags::kTemplate},
      {"textarea", Tags::kTextarea},
      {"tfoot", Tags::kTfoot},
      {"th", Tags::kTh},
      {"thead", Tags::kThead},
      {"time", Tags::kTime},
      {"title", Tags::kTitle},
      {"tr", Tags::kTr},
      {"track", Tags::kTrack},
      {"u", Tags::kU},
      {"ul", Tags::kUl},
      {"var", Tags::kVar},
      {"video", Tags::kVideo},
      {"wbr", Tags::kWbr},
  };

  auto it = tag_map.find(tag_name);
  if (it == tag_map.end()) {
    return Tags::kUnknown;
  }
  return it->second;
}

}  // namespace arboris
