"""Render the html5lib-tests tokenizer status table into README.md.

Reads the JUnit XML that pytest writes for the suite, groups the cases by the tokenizer
feature each one needs (tests/html5lib/categories.py), and rewrites the table between
the html5lib markers in README.md.

The headline figure is the unweighted mean of the six areas. A ratio over all cases
would mislead: namedEntities.test alone holds 2125 of them, so filling in the entity
table would carry the total from 47% to about 90% while attributes, comments and DOCTYPE
still emit no tokens at all.

Usage:
  pytest tests/html5lib -q --junitxml=html5lib.xml    # produce the input
  html5lib_status.py --junit html5lib.xml             # print the block
  html5lib_status.py --junit html5lib.xml --write     # rewrite README.md in place
  html5lib_status.py --junit html5lib.xml --check     # exit 1 if README.md is stale
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from collections import Counter
from pathlib import Path

from html5lib_junit import load_results

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tests" / "html5lib"))

from categories import MAJORS, Area, classify  # noqa: E402
from conftest import DATA_STATE, DEFAULT_TESTS_DIR, Case, load_cases  # noqa: E402

MARKER_START = "<!-- html5lib:start -->"
MARKER_END = "<!-- html5lib:end -->"


def percent(passed: int, total: int) -> int:
    """Floor, so one remaining failure can never round up to a finished 100%."""
    return passed * 100 // total if total else 0


def count_out_of_scope(tests_dir: Path) -> tuple[int, int]:
    """(broken HTML, needs state switching), counted the way conftest skips them."""
    broken = switching = 0
    for path in sorted(tests_dir.glob("*.test")):
        for test in json.loads(path.read_text(encoding="utf-8")).get("tests", []):
            if DATA_STATE not in test.get("initialStates", [DATA_STATE]):
                switching += 1
            elif test.get("errors"):
                broken += 1
    return broken, switching


def tally(cases: list[Case], results: dict[str, bool]) -> tuple[Counter[Area], Counter[Area]]:
    passed: Counter[Area] = Counter()
    total: Counter[Area] = Counter()
    for case in cases:
        area = classify(case)
        total[area] += 1
        if results.get(case.case_id, False):
            passed[area] += 1
    return passed, total


def render(cases: list[Case], results: dict[str, bool], tests_dir: Path) -> str:
    passed, total = tally(cases, results)
    rows = ["| Area | Passing | Rate |", "|---|---:|---:|"]
    rates: list[int] = []

    for major in MAJORS:
        features = sorted(
            (a for a in total if a.major == major), key=lambda a: (-total[a], a.feature)
        )
        major_passed = sum(passed[a] for a in features)
        major_total = sum(total[a] for a in features)
        rate = percent(major_passed, major_total)
        rates.append(rate)
        rows.append(f"| **{major}** | **{major_passed} / {major_total}** | **{rate}%** |")
        # One feature says no more than its area already did.
        if len(features) > 1:
            for area in features:
                share = percent(passed[area], total[area])
                rows.append(f"| ↳ {area.feature} | {passed[area]} / {total[area]} | {share}% |")

    overall = sum(rates) // len(rates)
    in_scope_passed = sum(passed.values())
    in_scope = sum(total.values())
    broken, switching = count_out_of_scope(tests_dir)

    return "\n".join(
        [
            MARKER_START,
            "",
            f"**{overall}% conformant** — the unweighted mean of the six area rates below.",
            "",
            *rows,
            "",
            f"<sub>{in_scope_passed} of {in_scope} in-scope cases pass. Areas differ by orders of "
            "magnitude in case count, so that ratio is not the figure above. Out of scope: "
            f"{broken} broken-HTML cases and {switching} that need tokenizer state switching. "
            "Generated by <code>scripts/html5lib_status.py</code>.</sub>",
            "",
            MARKER_END,
        ]
    )


def splice(readme: str, block: str) -> str:
    start = readme.find(MARKER_START)
    end = readme.find(MARKER_END)
    if start < 0 or end < start:
        raise SystemExit(f"{MARKER_START} / {MARKER_END} not found in README.md")
    return readme[:start] + block + readme[end + len(MARKER_END) :]


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument("--junit", type=Path, required=True, help="JUnit XML of a suite run")
    parser.add_argument("--readme", type=Path, default=REPO / "README.md")
    parser.add_argument("--tests-dir", type=Path, default=DEFAULT_TESTS_DIR)
    parser.add_argument("--write", action="store_true", help="rewrite README.md in place")
    parser.add_argument("--check", action="store_true", help="exit 1 if README.md is stale")
    args = parser.parse_args()

    if not args.tests_dir.is_dir():
        raise SystemExit(
            f"html5lib-tests not found at {args.tests_dir}; configure CMake with "
            "-DARBORIS_HTML5LIB_TESTS=ON, set ARBORIS_BUILD_DIR, or pass --tests-dir"
        )

    block = render(load_cases(args.tests_dir), load_results(args.junit), args.tests_dir)

    if not (args.write or args.check):
        print(block)
        return 0

    readme = args.readme.read_text(encoding="utf-8")
    updated = splice(readme, block)

    if args.write:
        if updated != readme:
            args.readme.write_text(updated, encoding="utf-8")
            print(f"{args.readme}: updated")
        else:
            print(f"{args.readme}: already up to date")
        return 0

    if updated == readme:
        print(f"{args.readme}: up to date")
        return 0
    print(
        "\n".join(
            difflib.unified_diff(
                readme.splitlines(), updated.splitlines(), "README.md", "expected", lineterm=""
            )
        )
    )
    print(
        "\nREADME.md is out of date. Regenerate it with:\n"
        "  uv run --group test pytest tests/html5lib -q --junitxml=html5lib.xml\n"
        "  uv run --group test python scripts/html5lib_status.py --junit html5lib.xml --write"
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
